### ISSUE TITLE
Wrong Form Return

### ISSUE THREAD

**Issue by TeaRX27** [CoESS-UECal/COESS_System#16]
Member and Event forms are still redirecting to the Legacy Forms **Member.cs** and **Event.cs** instead of **MainMenu.cs**

**Comment by khrizthero24** [comment]
Issue Acknowledged. Will correct after merge to master.

**Comment by TeaRX27** [comment]
forgot to mention **Devmode.cs** is also not redirecting properly

**Comment by khrizthero24** [comment]
Members and Events now redirects correctly. Will check on Devmode.

**Comment by khrizthero24** [comment]
Devmode can now redirect correctly. Closing the issue.
